### ISSUE TITLE
feat(server): output graph JSON for covariate discovery algorithm

### ISSUE THREAD

**Issue by CoreyCole** [CoreyCole/HypDB#3]
In order to display the results of HypDB's covariate discovery algorithm, we need to output metadata for the function call that we can easily pass to the graph visualization library we decided on in #1

**Comment by pzli3** [comment]
Per Babak:

Start with an empty graph. 
We need undirected edge from outcome to the elements in the boundary.
We need a directed edge from parents to outcome.
The same for treatment

If treatment is parent of outcome:
draw directed arrow
If outcome is parent of treatment:
error/malformed query
Else draw dashed line (grey maybe? since the libraries don't support dashed)
